name: cubit_di_playground
description: "Flutter project to experiment with cubit & di"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  injectable: ^2.5.0
  get_it: ^8.0.0
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true